### ISSUE TITLE
Can't connect to private TestRail with TestRailSDK version 0.9

### ISSUE THREAD

**Issue by ansonliao** [RetailMeNot/TestRailSDK#26]
Dear Sir,
In the latest version TestRailSDK in Maven repository: `0.9`, I can connect to my personal TestRail of TestRail cloud, and get the information from the API of TestRail, for example, project name, project ID, Test suite name, Test suite ID.

But once I changed to my company private testrail ,I can't connect to it, I verified that I can connect to my private testrail with REST tool such as `POSTMAN`, but use the TestRailSDK with version 0.9, I got the error below:
```java
Exception in thread "main" java.lang.RuntimeException: Connection is null (probably hit timeout), check parameters for [https://192.168.118.152/index.php?/api/v2/get_projects]
	at com.rmn.testrail.service.TestRailService.getRESTRequest(TestRailService.java:518)
	at com.rmn.testrail.service.TestRailService.getEntityList(TestRailService.java:134)
	at com.rmn.testrail.service.TestRailService.getProjects(TestRailService.java:179)
```

Could you advise how to fix the problem?

**Comment by ansonliao** [comment]
please close this issue, found the problem, and the problem is private testrail instance issue.
